### ISSUE TITLE
笔记移动、复制问题

### ISSUE THREAD

**Issue by letsgo008** [leanote/desktop-app#100]
如果有二级目录，笔记只能移动到二级目录，不能移动到一级目录，没法点击。
例如：
AAAA
----BBBBB
----CCCCC
DDDD
DDDD目录中笔记或CCCC中笔记，移动、复制时只能点BBBBB、CCCCC，不能点AAAAA

**Comment by letsgo008** [comment]
这个有人关注吗？严重影响笔记本归档

**Comment by letsgo008** [comment]
@lealife

**Comment by ThaddeusJiang** [comment]
是的，我觉得这是一个bug。
近期比较忙，计划在6月1日之前修复。

**Comment by ThaddeusJiang** [comment]
@letsgo008 这个 bug 已经修复。
修复后，移动和复制笔记的使用方法：https://github.com/leanote/desktop-app/pull/146

验证后，请 Close 此 Issues。
