### ISSUE TITLE
#桌面版本1.0.2bug report

### ISSUE THREAD

**Issue by FindHao** [leanote/desktop-app#105]
#桌面版本1.0.2bug report
更新了新版本之后，会出现下面这种右侧空白的情况，非常频繁
![screenshot from 2015-12-08 11 06 07](https://cloud.githubusercontent.com/assets/3823240/11646726/c388eb7a-9d9b-11e5-8520-9aa1a309b24b.png)
#运行环境

+ ubuntu 14.04 x86_64

**Comment by FindHao** [comment]
markdown格式笔记。

**Comment by Blackrose** [comment]
网页版也有同样的问题，Linux客户端也同样，这个问题好像从0.9就一直存在了。

**Comment by lealife** [comment]
怎么重现?

**Comment by Blackrose** [comment]
保存多个markdown的文章，长时间不要关闭，再添加内容后，切换文章，就会出现空白页面，只能关闭后重新打开才能看到内容。发现之前导入的evernote的内容是正常的

**Comment by lealife** [comment]
@Blackrose 有时间可否做一个gif重现下? 谢谢

**Comment by Blackrose** [comment]
这个有点难度，要很长时间才出现。发现的时候，情况和 @FindHao 的截图一样了，好像是atom本身的问题。

**Comment by lealife** [comment]
@Blackrose 下一次出现的时候可否在群里@我呢

**Comment by Blackrose** [comment]
@lealife 什么群？软件有log文件么，出现问题可以提供一下

**Comment by lealife** [comment]
没有log

**Comment by lealife** [comment]
leanote 群 256076853

**Comment by FindHao** [comment]
bug已重现。现在找到了触发的机制。下面的txt是我桌面录制的，下载后改成mp4格式就行。
[leanotebug.txt](https://github.com/leanote/desktop-app/files/73671/leanotebug.txt)
重现的步骤：
在markdown格式的笔记上，点击右上角的编辑按钮，然后把右边的预览关掉，再点击预览按钮，则显示一片空白。

**Comment by lealife** [comment]
@FindHao 非常感谢!!, 我们会尽快修改
