### ISSUE TITLE
如何开发插件

### ISSUE THREAD

**Issue by lealife** [leanote/desktop-app#110]
Leanote 桌面端的插件机制还不完善, 欢迎各位讨论如此设计一套标准的插件机制.

## 插件目录

所有插件都放在 ` public/plugins` 下, 像常见的主题切换theme, 多语言切换 langs 都是插件.

![image](https://cloud.githubusercontent.com/assets/1699428/11745074/55bc3d1a-a050-11e5-80a3-f832027554ca.png)

## 插件文件结构
一个插件至少由两个文件组成, plugin.js, plugin.json. plugin.json是插件的一些说明, 现在其实还没用到. plugin.js是插件的主文件.

plugin.js的代码结构如下:

```javascript
/**
 * 语言设置插件
 */
define(function() {
	var setLang = {
		// 多语言支持
		langs: {
			'en-us': {
				'setLang': 'Langs',
			},
			'zh-cn': {
				'setLang': '语言设置',
			},
			'zh-hk': {
				'setLang': '語言設置',
			}
		},
		
		// app 打开前
		onOpen: function() {
		},

		// app 打开后
		onOpenAfter: function() {
		},

		// 关闭时需要运行的
		onClose: function() {
		}
	};
	return setLang;
});
```
怎么调用Api呢? 我们专们为插件设计了一个Api, api文件 `public/js/app/api.js`, 具体的方法可以在该文件中查看. 比如调用 `Api.note.getCurNote()` 来获取当前笔记.

**注意** 该Api还只是初始设计阶段, 很不完善. 而且现在的插件命名空间其实不独立, 完全可以通过调用`Note.getCurNote()` 来获取当前笔记. 为什么要设计一个Api, 就是为了以后能统一管理, 不至于混乱. 当然这部分需要标准化.

写好一个插件后, 需要在`config.js`添加该插件, 如:

```javascript
var Config = {
    "plugins": [
        "theme",
        "import_leanote",
        "import_evernote",
        "export_pdf",
        "export_html",
        "export_leanote",
        "export_evernote",
        "langs",
        "accounts"
    ]
};
```

**Comment by lealife** [comment]
任何问题, 欢迎留言讨论

**Comment by imcaffrey** [comment]
如此设计 --> 如何
