### ISSUE TITLE
项目文件实在是太大了，git clone了很久

### ISSUE THREAD

**Issue by Deardrops** [leanote/desktop-app#125]
对electron在win平台下的打包过程不是很理解，请问leanote是用什么工具编译的？

**Comment by imcaffrey** [comment]
electron-prebuilt?

**Comment by lealife** [comment]
没有electron的代码, 所以项目文件大和electron无关. 100多M不大, 因为你是在..., you know it

**Comment by lealife** [comment]
打包你查看electron文档
