### ISSUE TITLE
海外难下载

### ISSUE THREAD

**Issue by LiangWei88** [leanote/desktop-app#126]
海外链接百度云盘不稳定，建议有备用源。

**Comment by lealife** [comment]
你好, 已添加 sourceforge 下载.https://sourceforge.net/projects/leanote-desktop-app/files/1.0.5/
谢谢你的建议.

Original Message
Sender:Liang Weinotifications@github.com
Recipient:leanote/desktop-appdesktop-app@noreply.github.com
Date:星期一, 1月 11, 2016 10:14
Subject:[desktop-app] 海外难下载 (#126)


海外链接百度云盘不稳定，建议有备用源。

**Comment by imcaffrey** [comment]
@lealife 你可以每次把release给attach上编译好的, using github.

**Comment by lealife** [comment]
Github总是上传上不了, 而且没有下载统计


Original Message
Sender:SCaffreynotifications@github.com
Recipient:leanote/desktop-appdesktop-app@noreply.github.com
Cc:lifelifephp@gmail.com
Date:星期一, 1月 11, 2016 12:44
Subject:Re: [desktop-app] 海外难下载 (#126)


@lealife 你可以每次把release给attach上编译好的, using github.
