### ISSUE TITLE
项目文件中缺失grunt/gulp打包/发布命令，能否加入？

### ISSUE THREAD

**Issue by dusdong** [leanote/desktop-app#131]
不知道本项目是用什么方式打包发布的？能否加入？

**Comment by lealife** [comment]
打包请参考Electron的打包机制. 该前端前端没有压缩合并, 所以没有Gulp.


Original Message
Sender:dusdongnotifications@github.com
Recipient:leanote/desktop-appdesktop-app@noreply.github.com
Date:星期五, 1月 29, 2016 22:53
Subject:[desktop-app] 项目文件中缺失grunt/gulp打包/发布命令，能否加入？ (#131)


不知道本项目是用什么方式打包发布的？能否加入？

**Comment by dusdong** [comment]
好的，谢谢
