### ISSUE TITLE
2016-04-06 郭标问题提交（4） （Markdown syntax bug ）

### ISSUE THREAD

**Issue by guobiao-cn** [leanote/desktop-app#135]
![image](https://cloud.githubusercontent.com/assets/11533026/14314796/0d8f112e-fc2c-11e5-8aca-8d8c57c4f433.png)

![image](https://cloud.githubusercontent.com/assets/11533026/14314865/6ccf0676-fc2c-11e5-91e1-a515074c5d38.png)

**Comment by ThaddeusJiang** [comment]
这是一个关于 Markdown 语法的问题，并不是bug。

Markdown 有序列表：使用数字接着一个英文句点。
例如
```
1.  Bird
2.  McHale
3.  Parish
```
很重要的一点是，你在**列表标记上使用的数字并不会影响输出的 HTML 结果**，上面的列表所产生的 HTML 标记为：
```
<ol>
<li>Bird</li>
<li>McHale</li>
<li>Parish</li>
</ol>
```
所以无论你写成下面哪一种方式
```
1.  Bird
1.  McHale
1.  Parish
```
或
```
3. Bird
1. McHale
8. Parish
```
结果都是一样的。

参考：http://wowubuntu.com/markdown/#list
