### ISSUE TITLE
是否可以把 最左边的两栏收起来

### ISSUE THREAD

**Issue by oliveagle** [leanote/desktop-app#143]
![image](https://cloud.githubusercontent.com/assets/2270205/15065074/2040634e-138e-11e6-8c79-7e478a1222fa.png)

**Comment by lidongchao112358** [comment]
这个真的特别支持, 编辑+预览其实有点不够大
这两列能隐藏真的很不错

**Comment by oliveagle** [comment]
这个真的已经有了..... 
![image](https://cloud.githubusercontent.com/assets/2270205/15797493/18f27cf0-2a4d-11e6-8043-b612d7f469cb.png)


但是貌似github里边的issue 没有人管哦.
