### ISSUE TITLE
Mac版 Markdown笔记使用中文输入法时出现错位

### ISSUE THREAD

**Issue by LucasYuNju** [leanote/desktop-app#165]
正在输入的字体和已经输入的字体不一致
![image](https://cloud.githubusercontent.com/assets/6972169/17845342/c7b62a84-6873-11e6-935d-b07679d64bc9.png)

应该和输入法没关系，普通笔记没有这个问题

**Comment by lealife** [comment]
看这个图, 正在输入的字体是你电脑的输入法的字体

**Comment by xuyuri** [comment]
![image](https://user-images.githubusercontent.com/9264579/49226456-996dad00-f421-11e8-98c4-7612c9945327.png)
输入完了就变成这样了。。。这是什么情况？根本打不了汉字了
![image](https://user-images.githubusercontent.com/9264579/49226476-abe7e680-f421-11e8-835a-e3cc8790a671.png)

**Comment by lealife** [comment]
![image](https://user-images.githubusercontent.com/1699428/49227370-e6528300-f423-11e8-9f68-0150e5501be8.png)
这种情况请选择使用轻量编辑器
