### ISSUE TITLE
客户端同步图片到私有云的时候图片打不开是什么原因？

### ISSUE THREAD

**Issue by carlleton** [leanote/desktop-app#195]
如题，在客户端的图片是一个id，同步到私有云之后图片实际id换了，但是笔记里边的图片地址却没有换
比如，本地地址是leanote://file/getImage?fileId=585f4bc18111d644f0000007，
同步到服务器图片实际是这个地址，/api/file/getImage?fileId=585f4bd6b7128a1f7000001f，
但是同步的过程没有替换笔记里边的地址

**Comment by lealife** [comment]
你好, 你的自建服务器的版本是?

**Comment by lealife** [comment]
地址变化是正确的, 本地的图片用的本地的地址, web上用的web的地址

**Comment by carlleton** [comment]
按说同步到自建服务器上web端应该更新为web的，但是没有更新
我上午拿github上leanote-all直接clone下来的，windows环境自己弄的，然后windows客户端

**Comment by lealife** [comment]
@carlleton 你重新下载leanote-all再试试

**Comment by lealife** [comment]
你好, 请确保下conf/app.conf的site.url是否和桌面端填定的自建服务地址一样

**Comment by carlleton** [comment]
更新了，还是不行，更新到自建服务器上只是把!leanote://file/getImage?fileId=5861199099adf467cc000000变成了http://localhost:9000/api/file/getImage?fileId=5861199099adf467cc000000，里边的id没有变化。
site.url是http://localhost:9000，windows客户端用的是V2.1

**Comment by lealife** [comment]
你好, 可以先加群 http://leanote.leanote.com/post/Leanote-groups 找群主联调下

**Comment by lealife** [comment]
可以试试leanote开源测试站: http://demo.leanote.top

**Comment by lealife** [comment]
https://github.com/leanote/leanote/commit/964cf1a750c7f3487498c995d918c0c9c1c3e997
