### ISSUE TITLE
切换视图遗留Bug

### ISSUE THREAD

**Issue by lealife** [leanote/desktop-app#197]
Hi, @LucasYuNju 代码我今天看了下. 除了我将css全迁移到less上, 还有以下问题:

* 切换视图未国际化
* 切换后重新render列表, 但定位到第一个note. 有没有可能列表模板都用一个, 而是使用css来控制列表的显示?

**Comment by lealife** [comment]
Hi, 有进展没, 计划这周上一版 @LucasYuNju

**Comment by LucasYuNju** [comment]
我尽量今天做好吧

**Comment by lealife** [comment]
辛苦了
