### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by Kwadz** [leanote/desktop-app#208]
What do you think about a language selection to make the user able to choose English or Chinese?

**Comment by h2y** [comment]
the App has the selection in the left-bottom menu.

**Comment by Kwadz** [comment]
I didn't see it, may be because I ran the project with Electron. I'm going to try with the downloadable file on Baidu. About that, to make international users at ease, I think we should also offer an english speaking website to download the file. In addition the current hosting is very busy, it's difficult to download the file (more than 1 hour from France).

**Comment by h2y** [comment]
http://leanote.org/

you can download from sourceforge at the official website.

**Comment by Kwadz** [comment]
Yes, even for the app, thank you.
