### ISSUE TITLE
最新版支持导入为知笔记？求方法

### ISSUE THREAD

**Issue by h2y** [leanote/desktop-app#209]
![image](https://cloud.githubusercontent.com/assets/12909077/21576840/c19019a8-cf7a-11e6-8f55-d0c82a020fb5.png)

看到更新公告说支持导入 HTML 和 为知笔记，激动的立即下载来试用。但是却找不见导入按钮？

使用的是 v2.2.1

**Comment by yueludanfeng** [comment]
点击work-->右键-->导入-->html/wiz
不过说实话，lenote现在还太慢了，打开慢，搜索慢（而且关键字还不标记），而且最新版居然连图片都不能直接粘贴（在前面一个版本是可以的），功能竟然还倒退啦，

**Comment by h2y** [comment]
谢谢，

毕竟不是商业公司的产品，只有等待完善咯~
