### ISSUE TITLE
How to change the theme?

### ISSUE THREAD

**Issue by Kwadz** [leanote/desktop-app#211]
How can we change the theme? I didn't find documentation about that.

**Comment by LucasYuNju** [comment]
You can switch to English first. In the setting menu:
![image](https://cloud.githubusercontent.com/assets/6972169/21591599/9c6a69ea-d140-11e6-919b-092cad444803.png)

And then change theme:
![image](https://cloud.githubusercontent.com/assets/6972169/21591637/e77bb146-d140-11e6-8409-09947c28f5e5.png)

**Comment by Kwadz** [comment]
I didn't realize that the user name was a menu, thank you.
