### ISSUE TITLE
桌面版验证失败

### ISSUE THREAD

**Issue by sukkiCat** [leanote/desktop-app#295]
leanote网页版能登陆，但是桌面版一直提示密码或者用户名错误，改密码也没有用。

**Comment by PowerDos** [comment]
同样的问题，登陆网页版可以，PC端一直显示密码或者用户名错误

**Comment by Ellean** [comment]
是自建的leanote嘛，若果是有没有考虑过是http或者https的区别呢？考虑到可能没有配置好Apache/Nginx/IIS或者证书导致的。

**Comment by lealife** [comment]
考虑是否是证书问题
