### ISSUE TITLE
Windows 客户端无法登陆

### ISSUE THREAD

**Issue by zaneyu** [leanote/desktop-app#3]
Hello,
首先感谢提供leanote这样好的一个产品。

我遇到的问题是，我无法使用我的 leanote 账号信息登陆 Windows 客户端。每次登陆都显示邮箱或密码错误。
但是同样的邮箱密码我可以在 Chrome 上直接登陆 leanote 。

**Comment by lealife** [comment]
非常抱歉, 这是一个BUG, 请先修改密码(不能包括特殊字符), 然后登录, 我们已经解决这个问题, 只是没有发布最新版本

**Comment by lealife** [comment]
leanote最新客户端已支持, 请至 http://app.leanote.com 下载

**Comment by zaneyu** [comment]
@lealife 感谢改进！

**Comment by BigZSmallY** [comment]
windows下改密码之后还是无法登录，心塞，还是不折腾了

**Comment by lealife** [comment]
@BigZSmallY 什么原因? 连接的是自建Leanote.或者公司有防火墙

**Comment by gougjp** [comment]
app支持配置代理吗, 一直无法登陆

**Comment by StupidYe** [comment]
我也是一直这样，但是web和手机可以登陆....求解决方法
