### ISSUE TITLE
WIN10桌面版严重BUG反馈

### ISSUE THREAD

**Issue by runningpig66** [leanote/desktop-app#311]
1.win环境桌面端编辑XML，输入带有style的标签，输入后保存，然后切换别的文档，再返回刚保存的文档，会返现带有style的XML代码段空白。如下图，好吧不能放图，BUG代码放上来
ProgressBar style="?android:attr/progressBarStyleHorizontal"请在内容左右加< 和 />，这里加上后，评论内容会显示不全
只要输入这种XML，然后保存，切换一下视图，回来看一定显示空白。
2.插入相同像素的图片，编辑时调整大小为200宽，按理说两张图片并排显示应该显示相同的大小，然后经常会出现显示大小不一致的问题。我已经找到了解决办法，就是一张一张的插入，调整好一张再放另一张，最后把图片放一行，显示的大小才相同。
3.选择要输入的代码语言后，出现的那个输入横条，按删除键，有时候可以删除，有时候按很多遍都无法删除。
4.还有很多BUG，都是小问题，比如只回车一次，却空格2行等。希望把第一个问题解决。第一个问题在网页编辑也会这样。其实在这条评论里加入这个标签，提交评论后也会看不到标签里的内容。

**Comment by lealife** [comment]
官网上还有这个问题吗?

**Comment by lealife** [comment]
http://leanote.leanote.com/post/Leanote-Desktop-v2.6.1-released
