### ISSUE TITLE
请问如果想要更换内置的markdown编辑器要怎么做？

### ISSUE THREAD

**Issue by gzz2000** [leanote/desktop-app#321]
我发现了一个比较好用的codemirror的markdown编辑器，想要移植到桌面端里用，请问我应该怎么做？编辑器的代码在哪个文件里？编辑器和程序是怎么耦合起来的？还要实现类似的粘贴图片这种功能，需要把图片数据上传到服务端的api之类的...之前的编辑器对emacs操作习惯的支持很有限，连按住shift选中文字都不支持，想要从外部复制粘贴文本都要C-x C-c，C-x C-v这样，想要改善下自己使用leanote的体验...谢谢！

**Comment by lealife** [comment]
这个比较麻烦, 要好好看看源码了

**Comment by lealife** [comment]
看源码...
