### ISSUE TITLE
想将笔记迁移到U盘，如何开启本地账户？

### ISSUE THREAD

**Issue by gensir** [leanote/desktop-app#322]
想将笔记迁移到U盘，如何开启本地账户？

**Comment by gensir** [comment]
能否本地+云方式 ，  本地存储位置可指定，

**Comment by automaticdai** [comment]
所有的数据文件在目录：

`C:\Users\USER_NAME\AppData\Roaming\Leanote`

我觉得把这个文件夹拷贝在U盘里，然后在新的电脑里覆盖所有数据就可以了。
我觉得本来就是云笔记，本地数据存储在哪里问题都不大。

**Comment by lealife** [comment]
桌面端数据目录:
http://leanote.leanote.com/post/Leanote-desktop-backup
