### ISSUE TITLE
想咨询下这个是官方的开发库吗，为何编译出来和官方下载的不一样？

### ISSUE THREAD

**Issue by hairichuhe** [leanote/desktop-app#325]
想咨询下这个是官方的开发库吗，为何编译出来和官方下载的不一样？我自己编译出来的，界面是这样的。
![111](https://user-images.githubusercontent.com/16095730/50394544-42959200-0799-11e9-819e-c7703803e208.png)
![222](https://user-images.githubusercontent.com/16095730/50394548-47f2dc80-0799-11e9-9d04-2d65e066ff8b.png)

**Comment by lealife** [comment]
是官方的

**Comment by lealife** [comment]
开发文档: https://github.com/leanote/desktop-app/wiki
