### ISSUE TITLE
相关版本是多少呀？？

### ISSUE THREAD

**Issue by lhsaq2009** [leanote/desktop-app#328]
node  你用的什么版本？
electron 用的什么版本？

**Comment by lhs472194266** [comment]
electron 我换了 4.0.4 和 2.0.17  总是遇到奇奇怪怪得错误。

**Comment by 836883740** [comment]
TypeError: app.makeSingleInstance is not a function

**Comment by 836883740** [comment]
TypeError: app.makeSingleInstance is not a function 是版本原因造成的吗？

**Comment by donaldtone** [comment]
官方的electron是1.1.1版本。
其他文件不做更新的话，可以使用到1.3.15版本的electron。
修正ace版本至1.2.6以上，解决了ace的markdown中文输入bug，可以使用至3.1.8版本的electron。
修改main.js，解决了app.makeSingleInstance这个electron api问题，可以使用至最新4.1.4版本的electron。

**Comment by lealife** [comment]
@donaldtone 正解

**Comment by lealife** [comment]
@donaldtone 
你提的这些能否提交个pull request? 多谢
`app.makeSingleInstance` 这个已解决.
