### ISSUE TITLE
tinymce编辑器的工具栏缺少了searchreplace工具

### ISSUE THREAD

**Issue by donaldtone** [leanote/desktop-app#331]
桌面客户端
desktop-app/public/js/app/page.js
行号551
		toolbar2 : "outdent indent blockquote | link unlink | table | hr removeformat | subscript superscript |searchreplace | pastetext | leanote_ace_pre | fontselect fontsizeselect",

searchreplace前面少了一个空格，导致searchreplace图标丢失。

改为如下，就出现了“find and replace”工具。
		toolbar2 : "outdent indent blockquote | link unlink | table | hr removeformat | subscript superscript | searchreplace | pastetext | leanote_ace_pre | fontselect fontsizeselect",

![image](https://user-images.githubusercontent.com/23021576/55523393-f63ed580-5656-11e9-984f-d382bb11a075.png)

**Comment by donaldtone** [comment]
其实leanote的服务器端也有这个问题，导致网页leanote也缺少了这个工具。
不过直接修改page.js 文件好像不行。
估计需要重新编译。

**Comment by donaldtone** [comment]
leanote的服务器需要更改的文件是app.min.js
目录是\leanote\leanote\public\js

**Comment by lealife** [comment]
谢谢, 已解决, 还没发布, 请使用快捷键暂时解决:

* windows: ctrl + f
* mac: command + f
