### ISSUE TITLE
使用electron-packager打包win无法运行

### ISSUE THREAD

**Issue by Mrzyxing** [leanote/desktop-app#336]
- sourcecode：
branch：master
commit: 
5d456c90...72a0d7 
2018/12/11 17:46:43
fetch api with current version param

- env:
windows7 pro 32G/2C

- cmd：
```
electron-packager . --platform=win32 --out target --arch=x64 --electron-version=4.1.4
```

problem：
![image](https://user-images.githubusercontent.com/15867085/56259975-b0c6e180-6107-11e9-981e-c04a6472b66a.png)

图显示不出来，下面是文字版:
uncaught exception:
TypeError:app.makeSingleInstance is not a function
  at Object.<anonymous>
(....\resources\app\main.js:24:24)
...
(....\resources\app\main.js:278:3)
  at Module._compile(internal/moules/cjs/loader.js:693:30
...
(....\resources\electron.asar\b...8)

**Comment by donaldtone** [comment]
// single instance
// const shouldQuit = app.makeSingleInstance((commandLine, workingDirectory) => {
  const shouldQuit = app.requestSingleInstanceLock()
  if (!shouldQuit) {
  app.quit()
} else {
    app.on('second-instance',  (event, commandLine, workingDirectory)  => {
   // Someone tried to run a second instance, we should focus our window.
  if (mainWindow) {
    mainWindow.show();
    if (mainWindow.isMinimized()) {
      mainWindow.restore();
    }
    mainWindow.focus();
  }
})
//  app.on('ready',createWindow)
}

// if (shouldQuit) {
//  app.quit()
//}

**Comment by donaldtone** [comment]
其实shouldquit改名为shouldrun更合理些。
不过也就是个名字，不影响程序使用。

**Comment by Mrzyxing** [comment]
> 其实shouldquit改名为shouldrun更合理些。
> 不过也就是个名字，不影响程序使用。



我按照你的代码打包了，问题的确解决了，但是发现依赖有问题(nedb not found)，看起来还是打包的问题，node_module中的第三方项目并没有导进来，我完全copy源码中的过来，结果样式也不对……

实在不好意思，对nodejs这一块不是很熟悉。但是笔记又都存在蚂蚁笔记了，所以还是很想自定义一下。
能麻烦给一下你这边的打包流程吗？或者有相应的blog我去读一遍也行，目前发现github上没有打包的教程，想看也不知道从何下手。

**Comment by donaldtone** [comment]
我是如下做的：
目录结构：主目录app，次级目录data/dev/docs/node_modules/public/tests，都是源码copy的。
1. 重新更新了node_module里面的依赖包，
用npm install xxx 的方式，手工把adm-zip async iconv-lite nedb needle node-getmac resanitize xml2js 都安装了一次。如果提示缺少组件，就用npm install xxx安装。
2. 用leanote-logo里面的icn文件，用icofx3 转为了leanote.ico文件。
3. 按照源码安装教程，在dev目录里面，运行gulp脚本
4. 在app的同级目录里面，运行electron packager的打包脚本
electron-packager .\app leanote --out .\dist-app --platform=win32 --arch=x64 --electron-version 4.1.4 --app-version 2.6.2 --overwrite --icon=.\app\leanote.ico
5. 运行结束，如果发现node_modules里面的文件没有copy到dist-app目录里面，就手工copy过去。
6. 应该就可以运行leanote了。

**Comment by donaldtone** [comment]
我用的package.json 文件如下
{
  "name": "leanote",
  "version": "2.6.2",
  "description": "note taking",
  "main": "main.js",
  "directories": {
    "doc": "docs",
    "test": "tests"
  },
  "scripts": {
    "start": "electron ."
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/leanote/desktop-app.git"
  },
  "keywords": [
    "note",
    "leanote"
  ],
  "author": "leanote",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/leanote/desktop-app/issues"
  },
  "homepage": "https://github.com/leanote/desktop-app#readme",
 "dependencies": {
    "adm-zip": {
      "version": "0.4.13",
      "resolved": "https://registry.npmjs.org/adm-zip/-/adm-zip-0.4.13.tgz",
      "integrity": "sha512-fERNJX8sOXfel6qCBCMPvZLzENBEhZTzKqg6vrOW5pvoEaQuJhRU4ndTAh6lHOxn1I6jnz2NHra56ZODM751uw=="
    },
    "async": {
      "version": "2.6.2",
      "resolved": "https://registry.npmjs.org/async/-/async-2.6.2.tgz",
      "integrity": "sha512-H1qVYh1MYhEEFLsP97cVKqCGo7KfCyTt6uEWqsTBr9SO84oK9Uwbyd/yCW+6rKJLHksBNUVWZDAjfS+Ccx0Bbg==",
      "requires": {
        "lodash": "^4.17.11"
      }
    },
    "binary-search-tree": {
      "version": "0.2.5",
      "resolved": "https://registry.npmjs.org/binary-search-tree/-/binary-search-tree-0.2.5.tgz",
      "integrity": "sha1-fbs7IQ/coIJFDa0jNMMErzm9x4Q=",
      "requires": {
        "underscore": "~1.4.4"
      }
    },
    "debug": {
      "version": "2.6.9",
      "resolved": "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz",
      "integrity": "sha512-bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==",
      "requires": {
        "ms": "2.0.0"
      }
    },
    "iconv-lite": {
      "version": "0.4.24",
      "resolved": "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.24.tgz",
      "integrity": "sha512-v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA==",
      "requires": {
        "safer-buffer": ">= 2.1.2 < 3"
      }
    },
    "immediate": {
      "version": "3.0.6",
      "resolved": "https://registry.npmjs.org/immediate/-/immediate-3.0.6.tgz",
      "integrity": "sha1-nbHb0Pr43m++D13V5Wu2BigN5ps="
    },
    "lie": {
      "version": "3.1.1",
      "resolved": "https://registry.npmjs.org/lie/-/lie-3.1.1.tgz",
      "integrity": "sha1-mkNrLMd0bKWd56QfpGmz77dr2H4=",
      "requires": {
        "immediate": "~3.0.5"
      }
    },
    "localforage": {
      "version": "1.7.3",
      "resolved": "https://registry.npmjs.org/localforage/-/localforage-1.7.3.tgz",
      "integrity": "sha512-1TulyYfc4udS7ECSBT2vwJksWbkwwTX8BzeUIiq8Y07Riy7bDAAnxDaPU/tWyOVmQAcWJIEIFP9lPfBGqVoPgQ==",
      "requires": {
        "lie": "3.1.1"
      }
    },
    "lodash": {
      "version": "4.17.11",
      "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.11.tgz",
      "integrity": "sha512-cQKh8igo5QUhZ7lg38DYWAxMvjSAKG0A8wGSVimP07SIUEK2UO+arSRKbRZWtelMtN5V0Hkwh5ryOto/SshYIg=="
    },
    "minimist": {
      "version": "0.0.8",
      "resolved": "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz",
      "integrity": "sha1-hX/Kv8M5fSYluCKCYuhqp6ARsF0="
    },
    "mkdirp": {
      "version": "0.5.1",
      "resolved": "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz",
      "integrity": "sha1-MAV0OOrGz3+MR2fzhkjWaX11yQM=",
      "requires": {
        "minimist": "0.0.8"
      }
    },
    "ms": {
      "version": "2.0.0",
      "resolved": "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz",
      "integrity": "sha1-VgiurfwAvmwpAd9fmGF4jeDVl8g="
    },
    "nedb": {
      "version": "1.8.0",
      "resolved": "https://registry.npmjs.org/nedb/-/nedb-1.8.0.tgz",
      "integrity": "sha1-DjUCzYLABNU1WkPJ5VV3vXvZHYg=",
      "requires": {
        "async": "0.2.10",
        "binary-search-tree": "0.2.5",
        "localforage": "^1.3.0",
        "mkdirp": "~0.5.1",
        "underscore": "~1.4.4"
      },
      "dependencies": {
        "async": {
          "version": "0.2.10",
          "resolved": "https://registry.npmjs.org/async/-/async-0.2.10.tgz",
          "integrity": "sha1-trvgsGdLnXGXCMo43owjfLUmw9E="
        }
      }
    },
    "needle": {
      "version": "2.2.4",
      "resolved": "https://registry.npmjs.org/needle/-/needle-2.2.4.tgz",
      "integrity": "sha512-HyoqEb4wr/rsoaIDfTH2aVL9nWtQqba2/HvMv+++m8u0dz808MaagKILxtfeSN7QU7nvbQ79zk3vYOJp9zsNEA==",
      "requires": {
        "debug": "^2.1.2",
        "iconv-lite": "^0.4.4",
        "sax": "^1.2.4"
      }
    },
    "node-getmac": {
      "version": "1.0.3",
      "resolved": "https://registry.npmjs.org/node-getmac/-/node-getmac-1.0.3.tgz",
      "integrity": "sha512-HEmIX5vFfYgpAH/MHiKgx4g7gCHWkBlmH+8huPk1d2cj73yKAdwcXqEykLpEzcRzIAUrAvd0sZhM/UKURS4xZA=="
    },
    "resanitize": {
      "version": "0.3.0",
      "resolved": "https://registry.npmjs.org/resanitize/-/resanitize-0.3.0.tgz",
      "integrity": "sha1-38sr8q4d8oOEOe1s0Ex4hFxTI1M=",
      "requires": {
        "validator": "~9.4.1"
      },
      "dependencies": {
        "validator": {
          "version": "9.4.1",
          "resolved": "https://registry.npmjs.org/validator/-/validator-9.4.1.tgz",
          "integrity": "sha512-YV5KjzvRmSyJ1ee/Dm5UED0G+1L4GZnLN3w6/T+zZm8scVua4sOhYKWTUrKa0H/tMiJyO9QLHMPN+9mB/aMunA=="
        }
      }
    },
    "safer-buffer": {
      "version": "2.1.2",
      "resolved": "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz",
      "integrity": "sha512-YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg=="
    },
    "sax": {
      "version": "1.2.4",
      "resolved": "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz",
      "integrity": "sha512-NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw=="
    },
    "underscore": {
      "version": "1.4.4",
      "resolved": "https://registry.npmjs.org/underscore/-/underscore-1.4.4.tgz",
      "integrity": "sha1-YaajIBBiKvoHljvzJSA88SI51gQ="
    },
    "validator": {
      "version": "10.11.0",
      "resolved": "https://registry.npmjs.org/validator/-/validator-10.11.0.tgz",
      "integrity": "sha512-X/p3UZerAIsbBfN/IwahhYaBbY68EN/UQBWHtsbXGT5bfrH/p4NQzUCG1kF/rtKaNpnJ7jAu6NGTdSNtyNIXMw=="
    },
    "xml2js": {
      "version": "0.4.19",
      "resolved": "https://registry.npmjs.org/xml2js/-/xml2js-0.4.19.tgz",
      "integrity": "sha512-esZnJZJOiJR9wWKMyuvSE1y6Dq5LCuJanqhxslH2bxM6duahNZ+HMpCLhBQGZkbX6xRf8x1Y2eJlgt2q3qo49Q==",
      "requires": {
        "sax": ">=0.6.0",
        "xmlbuilder": "~9.0.1"
      }
    },
    "xmlbuilder": {
      "version": "9.0.7",
      "resolved": "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-9.0.7.tgz",
      "integrity": "sha1-Ey7mPS7FVlxVfiD0wi35rKaGsQ0="
    }
  }
}

**Comment by Mrzyxing** [comment]
@donaldtone 你好，按照你的步骤发现package.json中很多dependencies和你的版本不一样，请问你这个信息是怎么生成的了？应该是有脚本生成，不可能要一个一个手工添加吧

**Comment by donaldtone** [comment]
这个是npm安装的时候，自动添加的。
真正的package脚本是
类似这样：
"dependencies": {
"xml2js":  "^0.4.19",
````
}

**Comment by donaldtone** [comment]
发现electron 5在5天前出来了正式版，试了一下，需要做如下改动就可以运行。
只在windows 7下测试过。
改主目录下的main.js

mainWindow = new BrowserWindow({
	  width: 1050, 
      height: 595,
      //frame: false,
     // frame: process.platform != 'darwin', 
     // transparent: false,
	  webPreferences: {
		  contextIsolation: false,
		  nodeIntegration: true,
    webviewTag: true
  }
     }
  );
     mainWindow.setMenu(null);
  console.log('load: file://' + __dirname + '/note.html');

**Comment by donaldtone** [comment]
另外发现needle用2.3.0没问题。
升级到2.3.1，leanote app就无法运行。
问题是在needle/lib/needle.js里面的行号775-777的else后面的3句。
去掉了这3句，leanote app就运行正常了。原因不明。

      defaults[target_key] = obj[key];
    }   else {
   throw new Error('Invalid property for defaults:' + target_key);      
  }
  }

  return defaults;
