### ISSUE TITLE
我在Ubuntu系统下安装蚂蚁笔记linux客户端

### ISSUE THREAD

**Issue by 1179325921** [leanote/desktop-app#341]
![Selection_001](https://user-images.githubusercontent.com/39483844/59574971-feea6800-90eb-11e9-8ce5-d8c72ea2335a.png)
写的文件没办法保存啊，离开文件就没了

**Comment by 1179325921** [comment]
版本是：2.6.2,按ctrl+s保存不了

**Comment by PSilverQ** [comment]
加油，学好go一起来完善leanote

**Comment by YeFei572** [comment]
解决了吗？同样的问题

**Comment by 1179325921** [comment]
@YeFei572 没有,选择的别的客户端
