### ISSUE TITLE
 Harfbuzz version too old (1.2.1)

### ISSUE THREAD

**Issue by 217heidai** [leanote/desktop-app#347]
I got error like this '(Leanote:2238): Pango-ERROR **: 10:36:30.413: Harfbuzz version too old (1.2.1)'.
OS: manjaro 18.1.2
Harfbuzz version: 2.6.4-1

**Comment by zfhxi** [comment]
I think this may help, <https://github.com/leanote/leanote.com-issue/issues/144#issuecomment-541515846>

**Comment by 217heidai** [comment]
It works. Thank U
