### ISSUE TITLE
客户端几个bug

### ISSUE THREAD

**Issue by goodbest** [leanote/desktop-app#4]
1. 无法根据content生成格式化后的abstract
这样在博客首页看到的内容依然是markdown格式，abstract还要自己调成带格式的。

2. 图片、附件的路径和网页端不一致。
我知道客户端127.0.0.1那个会改成正常的，但是之后的path不同
网页端上传的图片，产生的url是 outputImage...
客户端产生的是api/getImage....

3. 标记笔记同步状态有误
如果在客户端新建笔记、写好内容后（中间不切换、不点击其他note，只在该笔记操作），按下同步按钮是无法把该笔记上传的。
必须要鼠标点击一下其他笔记的标题（abstract），然后才能把刚写好的笔记同步

4. 客户端选中某篇笔记，切换到网页端（彻底）删掉该篇笔记后，再点击客户端会crash

5. 自建https服务器+自定义域名后，客户端无法使用https连接。（这个可能是个人问题。）

**Comment by lealife** [comment]
谢谢, 欢迎提交pull request

**Comment by goodbest** [comment]
本issue的第5点，fix在这里
https://github.com/leanote/desktop-app/pull/5

**Comment by lealife** [comment]
3. 可以使用ctrl+s进行保存+同步, 其它点击其它笔记就自动保存当前笔记了, 所以再点击同步就都同步了

**Comment by lealife** [comment]
[1, 2, 4] 需要解决
