### ISSUE TITLE
markdown笔记会被异常覆盖

### ISSUE THREAD

**Issue by coolbit-in** [leanote/desktop-app#46]
多个markdown笔记会被最后一个编辑的markdown笔记覆盖。
![image](https://cloud.githubusercontent.com/assets/1282514/9708835/4de7c380-5554-11e5-878f-d9780e9ac752.png)
![image](https://cloud.githubusercontent.com/assets/1282514/9708847/7cad8b28-5554-11e5-948f-7ec7caa25e2b.png)
点击笔记就会被覆盖，不重启客户端点击恢复历史版本瞬间又被覆盖，只有重启客户端再点击历史版本才能恢复。搞得我都不敢用markdown笔记了。
mac端app

**Comment by coolbit-in** [comment]
Bug唤起时间不确定，运行时间越长发生的概率越大。

**Comment by lealife** [comment]
可能原因, 编辑器抛异常, 导致js失效

**Comment by lealife** [comment]
刷新笔记消失原因: 
```
1. 初始列表; curChangedSaveIt(), 无
2. changeNotebook: 
    2.1 curSave, 无
    2.2 clearAll() 将笔记信息, 标题清空!!

    这时, note's content render完, 设置该noteId为curNote, 结果, 标题没了!!

    -> 定位到某笔记本: curSave, 有, 则保存之
```

还有, 当是markdown时, markdown未初始就拿笔记内容, 此时失峁.
