### ISSUE TITLE
导入为知笔记/html笔记

### ISSUE THREAD

**Issue by sstiger1230** [leanote/desktop-app#69]
今天刚刚升级到0.8版本的Windows客户端。

在为知笔记中导出html格式的笔记，保存在本地硬盘。用浏览器打开一篇笔记，复制并粘贴到Leanote中，链接的图片没有能够自动保存到Leanote中。

到本地数据保存的目录中查看，images目录中多了很多类似“1445011057230_5.html” 这样的文件，应该是保存图片失败后生成的文件。

**Comment by lealife** [comment]
没有权限下载图片, 不好解决

**Comment by lealife** [comment]
只能控制在没有权限的情况下不下载成html了

**Comment by sstiger1230** [comment]
图片是保存在本地硬盘里的，怎么会没有权限？ 

难道是 Electron 的原因？  那么本地的html将如何导入Leanote呢？

**Comment by lealife** [comment]
@sstiger1230 复制的的图片链接地址是? 虽然图片在本地, 但为知笔记内的图片地址肯定不是本地地址.

**Comment by sstiger1230** [comment]
不好意思，回复晚了。

我的为知笔记内部的图片都是保存在本地的，我是把为知笔记导出为HTML后再用浏览器打开，并且复制粘贴进leanote的，笔记内的图片是一个本地地址。 

为知笔记导出html，类似用浏览器保存一个网页，页面中的图片自动保存在对应的子目录中。

**Comment by sstiger1230** [comment]
可以用chrome保存一篇网页，保存为 test.html，那么页面中对应的图片应该在 test_files 目录中，都保存在本地硬盘，是本地地址。

再用浏览器打开 test.html ，然后复制并粘贴到 leanote 中，图片现在是能够正常显示，但是如果右键点击图片选择另存为，则会提示文件不存在。

关闭 leanote ，并且删除本地的 test.html 、test_files文件和目录，再打开leanote，刚才粘贴的笔记中图片就显示不出来了。

**Comment by lealife** [comment]
@sstiger1230 保存网页后, 图片在网页里是相对地址. 把网页里的内容复制粘贴到笔记中, 笔记中的图片链接也是相对链接, 此时肯定找不到图片了.

**Comment by sstiger1230** [comment]
还真的是个问题，以前没有注意到。

**Comment by sstiger1230** [comment]
其实可以从另外一个角度考虑，保存在本地的html，不再通过打开html后复制粘贴到笔记本中，而是通过导入html功能，直接把html以及对应的图片直接导入。

这样是不是容易实现？

**Comment by lealife** [comment]
@sstiger1230 可以实现, 导入为知

**Comment by lealife** [comment]
v1.1实现

**Comment by chih7** [comment]
等完成导入为知笔记功能我就转到leanote上来🙄，为知笔记linux客户端没有高分屏支持，没法继续用下去了。
