### ISSUE TITLE
桌面版历史记录

### ISSUE THREAD

**Issue by sstiger1230** [leanote/desktop-app#70]
版本 0.8 ，Windows版。

一个比较奇特的状况：

打开一篇笔记，点击修改后，再点击工具栏右侧的那个向下的三角，展开工具栏。然后直接点击其他的笔记。

再重新点开最早的那篇笔记，就会发现增加了一条历史记录。如果第二次点击其他笔记后再次打开第一篇笔记，则又会增加一条历史记录。

这样点击修改并展开工具栏后，在多个笔记之间来回点击，最多会增加两条历史记录。

最后：

     还是希望能够增加一个保存按钮，在不满意修改的时候，可以不进行保存，放弃修改的。

**Comment by lealife** [comment]
历史记录多了, 表非常大, 导致不能加载.
方案: 仅保存10-50条笔记.
