### ISSUE TITLE
笔记对应的图片、附件问题

### ISSUE THREAD

**Issue by sstiger1230** [leanote/desktop-app#71]
这两天在测试，删除了笔记后，发现本地的images目录中对应的图片依然还在。 attachs 中的附件也在。

希望以后删除笔记的时候，能够把对应的图片、附件一同删除。

似乎当客户端创建的笔记比较容易同时删除图片，附件，因为感觉这些图片只对应一个笔记。

通过Web方式创建的笔记，如果添加笔记，我看了一下，似乎会浏览到本账号的所有图片，这样如果一个图片被两篇笔记使用， 好像就不能轻易删除了。

这个情况似乎是个问题。

**Comment by lealife** [comment]
附件可以在删除笔记时删除, 但图片确实是个问题

**Comment by lealife** [comment]
拆成两个issue:
https://github.com/leanote/desktop-app/issues/90
https://github.com/leanote/desktop-app/issues/89
