### ISSUE TITLE
有“修改”，也要有“完成”

### ISSUE THREAD

**Issue by rexlevin** [leanote/desktop-app#82]
现在只有“修改”按钮，没有“完成”按钮，修改完成后只能借助切换其他笔记来“完成”，希望能有“完成”按钮。

另：今天发现了一个同质的竞争者哟：https://b00st.io/ ，现在它只有mac的，谁知道什么时候加上其他平台的呢，看外观挺不错的，要精细点。

话说，leanote第二列显示笔记列表时，两两之间那么宽的空，反正当前点击的会有背景色，就别要留空了吧～～～～

**Comment by lealife** [comment]
"现在只有“修改”按钮，没有“完成”按钮，修改完成后只能借助切换其他笔记来“完成”，希望能有“完成”按钮。
" 
推荐使用快捷键 ctrl/cmd + e 来切换修改与完成

**Comment by rexlevin** [comment]
原来还有个快捷键，一直都没留意title提示。
非常感谢。
